kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: chluehr/phpmd
    auto_tag: true
    tags:
      - latest
      - '2.15.0'
      - '2.15'
      - '2'
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password


